<?php

namespace Laraeast\LaravelBootstrapForms\Enums;

use Illuminate\Support\Str;

enum Country: string
{
    case AW = 'AW';
    case AF = 'AF';
    case AO = 'AO';
    case AI = 'AI';
    case AX = 'AX';
    case AL = 'AL';
    case AD = 'AD';
    case AE = 'AE';
    case AR = 'AR';
    case AM = 'AM';
    case AS = 'AS';
    case AQ = 'AQ';
    case TF = 'TF';
    case AG = 'AG';
    case AU = 'AU';
    case AT = 'AT';
    case AZ = 'AZ';
    case BI = 'BI';
    case BE = 'BE';
    case BJ = 'BJ';
    case BQ = 'BQ';
    case BF = 'BF';
    case BD = 'BD';
    case BG = 'BG';
    case BH = 'BH';
    case BS = 'BS';
    case BA = 'BA';
    case BL = 'BL';
    case BY = 'BY';
    case BZ = 'BZ';
    case BM = 'BM';
    case BO = 'BO';
    case BR = 'BR';
    case BB = 'BB';
    case BN = 'BN';
    case BT = 'BT';
    case BV = 'BV';
    case BW = 'BW';
    case CF = 'CF';
    case CA = 'CA';
    case CC = 'CC';
    case CH = 'CH';
    case CL = 'CL';
    case CN = 'CN';
    case CI = 'CI';
    case CM = 'CM';
    case CD = 'CD';
    case CG = 'CG';
    case CK = 'CK';
    case CO = 'CO';
    case KM = 'KM';
    case CV = 'CV';
    case CR = 'CR';
    case CU = 'CU';
    case CW = 'CW';
    case CX = 'CX';
    case KY = 'KY';
    case CY = 'CY';
    case CZ = 'CZ';
    case DE = 'DE';
    case DJ = 'DJ';
    case DM = 'DM';
    case DK = 'DK';
    case DO = 'DO';
    case DZ = 'DZ';
    case EC = 'EC';
    case EG = 'EG';
    case ER = 'ER';
    case EH = 'EH';
    case ES = 'ES';
    case EE = 'EE';
    case ET = 'ET';
    case FI = 'FI';
    case FJ = 'FJ';
    case FK = 'FK';
    case FR = 'FR';
    case FO = 'FO';
    case FM = 'FM';
    case GA = 'GA';
    case GB = 'GB';
    case GE = 'GE';
    case GG = 'GG';
    case GH = 'GH';
    case GI = 'GI';
    case GN = 'GN';
    case GP = 'GP';
    case GM = 'GM';
    case GW = 'GW';
    case GQ = 'GQ';
    case GR = 'GR';
    case GD = 'GD';
    case GL = 'GL';
    case GT = 'GT';
    case GF = 'GF';
    case GU = 'GU';
    case GY = 'GY';
    case HK = 'HK';
    case HM = 'HM';
    case HN = 'HN';
    case HR = 'HR';
    case HT = 'HT';
    case HU = 'HU';
    case ID = 'ID';
    case IM = 'IM';
    case IN = 'IN';
    case IO = 'IO';
    case IE = 'IE';
    case IR = 'IR';
    case IQ = 'IQ';
    case IS = 'IS';
    case IL = 'IL';
    case IT = 'IT';
    case JM = 'JM';
    case JE = 'JE';
    case JO = 'JO';
    case JP = 'JP';
    case KZ = 'KZ';
    case KE = 'KE';
    case KG = 'KG';
    case KH = 'KH';
    case KI = 'KI';
    case KN = 'KN';
    case KR = 'KR';
    case KW = 'KW';
    case LA = 'LA';
    case LB = 'LB';
    case LR = 'LR';
    case LY = 'LY';
    case LC = 'LC';
    case LI = 'LI';
    case LK = 'LK';
    case LS = 'LS';
    case LT = 'LT';
    case LU = 'LU';
    case LV = 'LV';
    case MO = 'MO';
    case MF = 'MF';
    case MA = 'MA';
    case MC = 'MC';
    case MD = 'MD';
    case MG = 'MG';
    case MV = 'MV';
    case MX = 'MX';
    case MH = 'MH';
    case MK = 'MK';
    case ML = 'ML';
    case MT = 'MT';
    case MM = 'MM';
    case ME = 'ME';
    case MN = 'MN';
    case MP = 'MP';
    case MZ = 'MZ';
    case MR = 'MR';
    case MS = 'MS';
    case MQ = 'MQ';
    case MU = 'MU';
    case MW = 'MW';
    case MY = 'MY';
    case YT = 'YT';
    case NA = 'NA';
    case NC = 'NC';
    case NE = 'NE';
    case NF = 'NF';
    case NG = 'NG';
    case NI = 'NI';
    case NU = 'NU';
    case NL = 'NL';
    case NO = 'NO';
    case NP = 'NP';
    case NR = 'NR';
    case NZ = 'NZ';
    case OM = 'OM';
    case PK = 'PK';
    case PA = 'PA';
    case PN = 'PN';
    case PE = 'PE';
    case PH = 'PH';
    case PW = 'PW';
    case PG = 'PG';
    case PL = 'PL';
    case PR = 'PR';
    case KP = 'KP';
    case PT = 'PT';
    case PY = 'PY';
    case PS = 'PS';
    case PF = 'PF';
    case QA = 'QA';
    case RE = 'RE';
    case RO = 'RO';
    case RU = 'RU';
    case RW = 'RW';
    case SA = 'SA';
    case SD = 'SD';
    case SN = 'SN';
    case SG = 'SG';
    case GS = 'GS';
    case SH = 'SH';
    case SJ = 'SJ';
    case SB = 'SB';
    case SL = 'SL';
    case SV = 'SV';
    case SM = 'SM';
    case SO = 'SO';
    case PM = 'PM';
    case RS = 'RS';
    case SS = 'SS';
    case ST = 'ST';
    case SR = 'SR';
    case SK = 'SK';
    case SI = 'SI';
    case SE = 'SE';
    case SZ = 'SZ';
    case SX = 'SX';
    case SC = 'SC';
    case SY = 'SY';
    case TC = 'TC';
    case TD = 'TD';
    case TG = 'TG';
    case TH = 'TH';
    case TJ = 'TJ';
    case TK = 'TK';
    case TM = 'TM';
    case TL = 'TL';
    case TO = 'TO';
    case TT = 'TT';
    case TN = 'TN';
    case TR = 'TR';
    case TV = 'TV';
    case TW = 'TW';
    case TZ = 'TZ';
    case UG = 'UG';
    case UA = 'UA';
    case UM = 'UM';
    case UY = 'UY';
    case US = 'US';
    case UZ = 'UZ';
    case VA = 'VA';
    case VC = 'VC';
    case VE = 'VE';
    case VG = 'VG';
    case VI = 'VI';
    case VN = 'VN';
    case VU = 'VU';
    case WF = 'WF';
    case WS = 'WS';
    case YE = 'YE';
    case ZA = 'ZA';
    case ZM = 'ZM';
    case ZW = 'ZW';

    public function getFlag(): string
    {
        return match ($this) {
            self::AW => '🇦🇼',
            self::AF => '🇦🇫',
            self::AO => '🇦🇴',
            self::AI => '🇦🇮',
            self::AX => '🇦🇽',
            self::AL => '🇦🇱',
            self::AD => '🇦🇩',
            self::AE => '🇦🇪',
            self::AR => '🇦🇷',
            self::AM => '🇦🇲',
            self::AS => '🇦🇸',
            self::AQ => '🇦🇶',
            self::TF => '🇹🇫',
            self::AG => '🇦🇬',
            self::AU => '🇦🇺',
            self::AT => '🇦🇹',
            self::AZ => '🇦🇿',
            self::BI => '🇧🇮',
            self::BE => '🇧🇪',
            self::BJ => '🇧🇯',
            self::BQ => '🇧🇶',
            self::BF => '🇧🇫',
            self::BD => '🇧🇩',
            self::BG => '🇧🇬',
            self::BH => '🇧🇭',
            self::BS => '🇧🇸',
            self::BA => '🇧🇦',
            self::BL => '🇧🇱',
            self::BY => '🇧🇾',
            self::BZ => '🇧🇿',
            self::BM => '🇧🇲',
            self::BO => '🇧🇴',
            self::BR => '🇧🇷',
            self::BB => '🇧🇧',
            self::BN => '🇧🇳',
            self::BT => '🇧🇹',
            self::BV => '🇧🇻',
            self::BW => '🇧🇼',
            self::CF => '🇨🇫',
            self::CA => '🇨🇦',
            self::CC => '🇨🇨',
            self::CH => '🇨🇭',
            self::CL => '🇨🇱',
            self::CN => '🇨🇳',
            self::CI => '🇨🇮',
            self::CM => '🇨🇲',
            self::CD => '🇨🇩',
            self::CG => '🇨🇬',
            self::CK => '🇨🇰',
            self::CO => '🇨🇴',
            self::KM => '🇰🇲',
            self::CV => '🇨🇻',
            self::CR => '🇨🇷',
            self::CU => '🇨🇺',
            self::CW => '🇨🇼',
            self::CX => '🇨🇽',
            self::KY => '🇰🇾',
            self::CY => '🇨🇾',
            self::CZ => '🇨🇿',
            self::DE => '🇩🇪',
            self::DJ => '🇩🇯',
            self::DM => '🇩🇲',
            self::DK => '🇩🇰',
            self::DO => '🇩🇴',
            self::DZ => '🇩🇿',
            self::EC => '🇪🇨',
            self::EG => '🇪🇬',
            self::ER => '🇪🇷',
            self::EH => '🇪🇭',
            self::ES => '🇪🇸',
            self::EE => '🇪🇪',
            self::ET => '🇪🇹',
            self::FI => '🇫🇮',
            self::FJ => '🇫🇯',
            self::FK => '🇫🇰',
            self::FR => '🇫🇷',
            self::FO => '🇫🇴',
            self::FM => '🇫🇲',
            self::GA => '🇬🇦',
            self::GB => '🇬🇧',
            self::GE => '🇬🇪',
            self::GG => '🇬🇬',
            self::GH => '🇬🇭',
            self::GI => '🇬🇮',
            self::GN => '🇬🇳',
            self::GP => '🇬🇵',
            self::GM => '🇬🇲',
            self::GW => '🇬🇼',
            self::GQ => '🇬🇶',
            self::GR => '🇬🇷',
            self::GD => '🇬🇩',
            self::GL => '🇬🇱',
            self::GT => '🇬🇹',
            self::GF => '🇬🇫',
            self::GU => '🇬🇺',
            self::GY => '🇬🇾',
            self::HK => '🇭🇰',
            self::HM => '🇭🇲',
            self::HN => '🇭🇳',
            self::HR => '🇭🇷',
            self::HT => '🇭🇹',
            self::HU => '🇭🇺',
            self::ID => '🇮🇩',
            self::IM => '🇮🇲',
            self::IN => '🇮🇳',
            self::IO => '🇮🇴',
            self::IE => '🇮🇪',
            self::IR => '🇮🇷',
            self::IQ => '🇮🇶',
            self::IS => '🇮🇸',
            self::IL => '🇮🇱',
            self::IT => '🇮🇹',
            self::JM => '🇯🇲',
            self::JE => '🇯🇪',
            self::JO => '🇯🇴',
            self::JP => '🇯🇵',
            self::KZ => '🇰🇿',
            self::KE => '🇰🇪',
            self::KG => '🇰🇬',
            self::KH => '🇰🇭',
            self::KI => '🇰🇮',
            self::KN => '🇰🇳',
            self::KR => '🇰🇷',
            self::KW => '🇰🇼',
            self::LA => '🇱🇦',
            self::LB => '🇱🇧',
            self::LR => '🇱🇷',
            self::LY => '🇱🇾',
            self::LC => '🇱🇨',
            self::LI => '🇱🇮',
            self::LK => '🇱🇰',
            self::LS => '🇱🇸',
            self::LT => '🇱🇹',
            self::LU => '🇱🇺',
            self::LV => '🇱🇻',
            self::MO => '🇲🇴',
            self::MF => '🇲🇫',
            self::MA => '🇲🇦',
            self::MC => '🇲🇨',
            self::MD => '🇲🇩',
            self::MG => '🇲🇬',
            self::MV => '🇲🇻',
            self::MX => '🇲🇽',
            self::MH => '🇲🇭',
            self::MK => '🇲🇰',
            self::ML => '🇲🇱',
            self::MT => '🇲🇹',
            self::MM => '🇲🇲',
            self::ME => '🇲🇪',
            self::MN => '🇲🇳',
            self::MP => '🇲🇵',
            self::MZ => '🇲🇿',
            self::MR => '🇲🇷',
            self::MS => '🇲🇸',
            self::MQ => '🇲🇶',
            self::MU => '🇲🇺',
            self::MW => '🇲🇼',
            self::MY => '🇲🇾',
            self::YT => '🇾🇹',
            self::NA => '🇳🇦',
            self::NC => '🇳🇨',
            self::NE => '🇳🇪',
            self::NF => '🇳🇫',
            self::NG => '🇳🇬',
            self::NI => '🇳🇮',
            self::NU => '🇳🇺',
            self::NL => '🇳🇱',
            self::NO => '🇳🇴',
            self::NP => '🇳🇵',
            self::NR => '🇳🇷',
            self::NZ => '🇳🇿',
            self::OM => '🇴🇲',
            self::PK => '🇵🇰',
            self::PA => '🇵🇦',
            self::PN => '🇵🇳',
            self::PE => '🇵🇪',
            self::PH => '🇵🇭',
            self::PW => '🇵🇼',
            self::PG => '🇵🇬',
            self::PL => '🇵🇱',
            self::PR => '🇵🇷',
            self::KP => '🇰🇵',
            self::PT => '🇵🇹',
            self::PY => '🇵🇾',
            self::PS => '🇵🇸',
            self::PF => '🇵🇫',
            self::QA => '🇶🇦',
            self::RE => '🇷🇪',
            self::RO => '🇷🇴',
            self::RU => '🇷🇺',
            self::RW => '🇷🇼',
            self::SA => '🇸🇦',
            self::SD => '🇸🇩',
            self::SN => '🇸🇳',
            self::SG => '🇸🇬',
            self::GS => '🇬🇸',
            self::SH => '🇸🇭',
            self::SJ => '🇸🇯',
            self::SB => '🇸🇧',
            self::SL => '🇸🇱',
            self::SV => '🇸🇻',
            self::SM => '🇸🇲',
            self::SO => '🇸🇴',
            self::PM => '🇵🇲',
            self::RS => '🇷🇸',
            self::SS => '🇸🇸',
            self::ST => '🇸🇹',
            self::SR => '🇸🇷',
            self::SK => '🇸🇰',
            self::SI => '🇸🇮',
            self::SE => '🇸🇪',
            self::SZ => '🇸🇿',
            self::SX => '🇸🇽',
            self::SC => '🇸🇨',
            self::SY => '🇸🇾',
            self::TC => '🇹🇨',
            self::TD => '🇹🇩',
            self::TG => '🇹🇬',
            self::TH => '🇹🇭',
            self::TJ => '🇹🇯',
            self::TK => '🇹🇰',
            self::TM => '🇹🇲',
            self::TL => '🇹🇱',
            self::TO => '🇹🇴',
            self::TT => '🇹🇹',
            self::TN => '🇹🇳',
            self::TR => '🇹🇷',
            self::TV => '🇹🇻',
            self::TW => '🇹🇼',
            self::TZ => '🇹🇿',
            self::UG => '🇺🇬',
            self::UA => '🇺🇦',
            self::UM => '🇺🇲',
            self::UY => '🇺🇾',
            self::US => '🇺🇸',
            self::UZ => '🇺🇿',
            self::VA => '🇻🇦',
            self::VC => '🇻🇨',
            self::VE => '🇻🇪',
            self::VG => '🇻🇬',
            self::VI => '🇻🇮',
            self::VN => '🇻🇳',
            self::VU => '🇻🇺',
            self::WF => '🇼🇫',
            self::WS => '🇼🇸',
            self::YE => '🇾🇪',
            self::ZA => '🇿🇦',
            self::ZM => '🇿🇲',
            self::ZW => '🇿🇼',
        };
    }

    public function getDialCode(): string
    {
        return match ($this) {
            self::AW => '+297',
            self::AF => '+93',
            self::AO => '+244',
            self::AI, self::AS, self::VI, self::VG, self::VC, self::US, self::TT, self::TC, self::SX, self::PR, self::MS, self::MP, self::LC, self::KN, self::JM, self::GU, self::GD, self::DO, self::DM, self::KY, self::CA, self::BB, self::BM, self::BS, self::AG => '+1',
            self::AX, self::FI => '+358',
            self::AL => '+355',
            self::AD => '+376',
            self::AE => '+971',
            self::AR => '+54',
            self::AM => '+374',
            self::AQ, self::UM, self::GS, self::PN, self::HM, self::BV, self::TF => '+0',
            self::AU, self::CX, self::CC => '+61',
            self::AT => '+43',
            self::AZ => '+994',
            self::BI => '+257',
            self::BE => '+32',
            self::BJ => '+229',
            self::BQ, self::CW => '+599',
            self::BF => '+226',
            self::BD => '+880',
            self::BG => '+359',
            self::BH => '+973',
            self::BA => '+387',
            self::BL, self::MF, self::GP => '+590',
            self::BY => '+375',
            self::BZ => '+501',
            self::BO => '+591',
            self::BR => '+55',
            self::BN => '+673',
            self::BT => '+975',
            self::BW => '+267',
            self::CF => '+236',
            self::CH => '+41',
            self::CL => '+56',
            self::CN => '+86',
            self::CI => '+225',
            self::CM => '+237',
            self::CD => '+243',
            self::CG => '+242',
            self::CK => '+682',
            self::CO => '+57',
            self::KM => '+269',
            self::CV => '+238',
            self::CR => '+506',
            self::CU => '+53',
            self::CY => '+357',
            self::CZ => '+420',
            self::DE => '+49',
            self::DJ => '+253',
            self::DK => '+45',
            self::DZ => '+213',
            self::EC => '+593',
            self::EG => '+20',
            self::ER => '+291',
            self::EH, self::MA => '+212',
            self::ES => '+34',
            self::EE => '+372',
            self::ET => '+251',
            self::FJ => '+679',
            self::FK => '+500',
            self::FR => '+33',
            self::FO => '+298',
            self::FM => '+691',
            self::GA => '+241',
            self::GB, self::JE, self::IM, self::GG => '+44',
            self::GE => '+995',
            self::GH => '+233',
            self::GI => '+350',
            self::GN => '+224',
            self::GM => '+220',
            self::GW => '+245',
            self::GQ => '+240',
            self::GR => '+30',
            self::GL => '+299',
            self::GT => '+502',
            self::GF => '+594',
            self::GY => '+592',
            self::HK => '+852',
            self::HN => '+504',
            self::HR => '+385',
            self::HT => '+509',
            self::HU => '+36',
            self::ID => '+62',
            self::IN => '+91',
            self::IO => '+246',
            self::IE => '+353',
            self::IR => '+98',
            self::IQ => '+964',
            self::IS => '+354',
            self::IL => '+972',
            self::IT, self::VA => '+39',
            self::JO => '+962',
            self::JP => '+81',
            self::KZ, self::RU => '+7',
            self::KE => '+254',
            self::KG => '+996',
            self::KH => '+855',
            self::KI => '+686',
            self::KR => '+82',
            self::KW => '+965',
            self::LA => '+856',
            self::LB => '+961',
            self::LR => '+231',
            self::LY => '+218',
            self::LI => '+423',
            self::LK => '+94',
            self::LS => '+266',
            self::LT => '+370',
            self::LU => '+352',
            self::LV => '+371',
            self::MO => '+853',
            self::MC => '+377',
            self::MD => '+373',
            self::MG => '+261',
            self::MV => '+960',
            self::MX => '+52',
            self::MH => '+692',
            self::MK => '+389',
            self::ML => '+223',
            self::MT => '+356',
            self::MM => '+95',
            self::ME => '+382',
            self::MN => '+976',
            self::MZ => '+258',
            self::MR => '+222',
            self::MQ => '+596',
            self::MU => '+230',
            self::MW => '+265',
            self::MY => '+60',
            self::YT, self::RE => '+262',
            self::NA => '+264',
            self::NC => '+687',
            self::NE => '+227',
            self::NF => '+672',
            self::NG => '+234',
            self::NI => '+505',
            self::NU => '+683',
            self::NL => '+31',
            self::NO, self::SJ => '+47',
            self::NP => '+977',
            self::NR => '+674',
            self::NZ => '+64',
            self::OM => '+968',
            self::PK => '+92',
            self::PA => '+507',
            self::PE => '+51',
            self::PH => '+63',
            self::PW => '+680',
            self::PG => '+675',
            self::PL => '+48',
            self::KP => '+850',
            self::PT => '+351',
            self::PY => '+595',
            self::PS => '+970',
            self::PF => '+689',
            self::QA => '+974',
            self::RO => '+40',
            self::RW => '+250',
            self::SA => '+966',
            self::SD => '+249',
            self::SN => '+221',
            self::SG => '+65',
            self::SH => '+290',
            self::SB => '+677',
            self::SL => '+232',
            self::SV => '+503',
            self::SM => '+378',
            self::SO => '+252',
            self::PM => '+508',
            self::RS => '+381',
            self::SS => '+211',
            self::ST => '+239',
            self::SR => '+597',
            self::SK => '+421',
            self::SI => '+386',
            self::SE => '+46',
            self::SZ => '+268',
            self::SC => '+248',
            self::SY => '+963',
            self::TD => '+235',
            self::TG => '+228',
            self::TH => '+66',
            self::TJ => '+992',
            self::TK => '+690',
            self::TM => '+993',
            self::TL => '+670',
            self::TO => '+676',
            self::TN => '+216',
            self::TR => '+90',
            self::TV => '+688',
            self::TW => '+886',
            self::TZ => '+255',
            self::UG => '+256',
            self::UA => '+380',
            self::UY => '+598',
            self::UZ => '+998',
            self::VE => '+58',
            self::VN => '+84',
            self::VU => '+678',
            self::WF => '+681',
            self::WS => '+685',
            self::YE => '+967',
            self::ZA => '+27',
            self::ZM => '+260',
            self::ZW => '+263'
        };
    }

    public function getPhonePlaceholder(): string
    {
        return match ($this) {
            self::AW => '5XX XXXX',
            self::AF, self::TL, self::SN => '7X XXX XXXX',
            self::AO, self::PT, self::PE => '9XX XXX XXX',
            self::AI => '264 XXX XXXX',
            self::AS => '684 XXX XXXX',
            self::VI => '340 XXX XXXX',
            self::VG => '284 XXX XXXX',
            self::VC => '784 XXX XXXX',
            self::US, self::UM, self::CA => 'XXX XXX XXXX',
            self::TT => '868 XXX XXXX',
            self::TC => '649 XXX XXXX',
            self::SX => '721 XXX XXXX',
            self::PR => '787 XXX XXXX',
            self::MS => '664 XXX XXXX',
            self::MP => '670 XXX XXXX',
            self::LC => '758 XXX XXXX',
            self::KN => '869 XXX XXXX',
            self::JM => '876 XXX XXXX',
            self::GU => '671 XXX XXXX',
            self::GD => '473 XXX XXXX',
            self::DO => '809 XXX XXXX',
            self::DM => '767 XXX XXXX',
            self::KY => '345 XXX XXXX',
            self::BB => '246 XXX XXXX',
            self::BM => '441 XXX XXXX',
            self::BS => '242 XXX XXXX',
            self::AG => '268 XXX XXXX',
            self::AX => '18 XXX XXX',
            self::FI => '4X XXX XXXX',
            self::AL, self::NL => '6X XXX XXXX',
            self::AD, self::GS => 'XXX XXX',
            self::AE, self::AZ => '5X XXX XXXX',
            self::AR => '9 11 XXXX XXXX',
            self::AM, self::GW => '9X XXX XXX',
            self::AQ => 'XXXXXXXX',
            self::PN, self::TF, self::BV => 'XXX XXXX',
            self::HM => 'X XXXX XXXX',
            self::AU => '4XX XXX XXX',
            self::CX, self::CC => '8 XXXX XXXX',
            self::AT => '6XX XXX XXXX',
            self::BI, self::WS, self::SZ => '7X XX XXXX',
            self::BE => '4XX XX XX XX',
            self::BJ, self::TG, self::NE => '9X XX XX XX',
            self::BQ, self::SR, self::GM, self::BO => '7XX XXXX',
            self::CW => '9XX XXXX',
            self::BF, self::TD, self::LU => '6X XX XX XX',
            self::BD => '01XXX XXXXXX',
            self::BG => '08X XXX XXX',
            self::BH => '3XXXXXXX',
            self::BA, self::RS, self::ME, self::EH => '06X XXX XXX',
            self::BL, self::PM, self::GP, self::MF => '690 XX XX XX',
            self::BY => '2X XXX XXXX',
            self::BZ, self::MO, self::IS, self::GY => '6XX XXXX',
            self::BR => '9XXXX XXXX',
            self::BN => '7XXX XXXX',
            self::BT => '17X XXX XX',
            self::BW => '7X XXX XXX',
            self::CF => '70 XX XX XX',
            self::CH => '07X XXX XX XX',
            self::CL => '9 XXXX XXXX',
            self::CN => '1XX XXXX XXXX',
            self::CI => '01 XX XX XXX',
            self::CM => '6XX XX XX XX',
            self::CD => '09X XXX XXXX',
            self::CG => '06X XXX XXX',
            self::CK => '7XXX',
            self::CO => '3XX XXX XXXX',
            self::KM => '32 XX XXX',
            self::CV => '9XX XX XX',
            self::CR => '6XXXXXXX',
            self::CU => '5XX XXXX',
            self::CY => '9X XXX XXX',
            self::CZ => '6XX XXX XXX',
            self::DE => '15X XXXX XXXX',
            self::DJ => '77 XX XX XX',
            self::DK => '2X XX XX XX',
            self::DZ => '05XX XX XX XX',
            self::EC, self::VN, self::UA, self::TH, self::SS, self::SD, self::LY, self::HR, self::ET => '09X XXX XXXX',
            self::EG => '01X XXXX XXXX',
            self::ER, self::ZW, self::UG, self::SL, self::RW, self::MK, self::LR => '07X XXX XXX',
            self::MA, self::ZA, self::HU => '06X XXX XXXX',
            self::ES => '6XX XXX XXX',
            self::EE, self::LS, self::GI => '5XXXXXXX',
            self::FJ => '7XXX XXX',
            self::FK => '5XXXXX',
            self::FR => '06 XX XX XX XX',
            self::FO, self::GL => '2XXXXXX',
            self::FM => '3XX XXXX',
            self::GA => '06 XX XX XX',
            self::GB, self::GG, self::IM, self::JE => '07XXX XXXXXX',
            self::GE => '5XX XX XX XX',
            self::GH, self::TR, self::SA, self::IL => '05X XXX XXXX',
            self::GN, self::TM => '6X XXX XXX',
            self::GQ => '222 XXX XXX',
            self::GR => '69X XXX XXXX',
            self::GT, self::MU, self::KW => '5XXX XXXX',
            self::GF => '694 XX XX XX',
            self::HK, self::OM => '9XXXXXXX',
            self::HN => '9XXX XXXX',
            self::HT => '3X XX XXXX',
            self::ID => '08XX XXX XXXX',
            self::IN => '9XXXX XXXXX',
            self::IO => '38XXX XXXXX',
            self::IE => '08X XXX XXXX',
            self::IR, self::PH => '09XX XXX XXXX',
            self::IQ, self::TZ, self::SE, self::RO, self::LK => '07X XXX XXXX',
            self::IT, self::VA => '3XX XXX XXXX',
            self::JO => '07X XXXX XXX',
            self::JP => '090 XXXX XXXX',
            self::KZ => '7XX XXX XXXX',
            self::RU => '9XX XXX XXXX',
            self::KE => '07XX XXX XXX',
            self::KG => '7XX XXX XXX',
            self::KH => '0XX XXX XXX',
            self::KI, self::SB => '7XXXX',
            self::KR => '010 XXXX XXXX',
            self::LA => '020 XXXX XXX',
            self::LB => '03 XXX XXX',
            self::LI => '6XX XX XX',
            self::LT => '6XX XXXXX',
            self::LV => '2XXXXXXX',
            self::MC => '6XX XX XX XX',
            self::MD => '06X XXXXXX',
            self::MG => '032 XX XXX XX',
            self::MV => '7XXXXXX',
            self::MX => '55 XXXX XXXX',
            self::MH => '235 XXXX',
            self::ML => '7X XX XX XX',
            self::MT => '99 XX XX XX',
            self::MM => '09 XXX XXX XXX',
            self::MN => '8XX XXXX',
            self::MZ => '8X XXX XXX',
            self::MR => '2X XX XX XX',
            self::MQ => '696 XX XX XX',
            self::MW => '099X XXX XXX',
            self::MY => '01X XXX XXXX',
            self::YT, self::RE => '639 XX XX XX',
            self::NA => '081 XXX XXXX',
            self::NC => '75 XX XX',
            self::NF => '3XXXX',
            self::NG => '080X XXX XXXX',
            self::NI => '8XXXXXXX',
            self::NU, self::TK => '4XXX',
            self::NO, self::SJ => '4XX XX XXX',
            self::NP => '98X XXX XXXX',
            self::NR => '555 XXXX',
            self::NZ => '02X XXX XXXX',
            self::PK => '03XX XXXXXXX',
            self::PA => '6XXX XXXX',
            self::PW => '779 XXXX',
            self::PG, self::SV => '7XXX XXXX',
            self::PL => '5XX XXX XXX',
            self::KP => '0192 XXX XXX',
            self::PY, self::ZM, self::UY, self::SY, self::SK => '09X XXX XXX',
            self::PS => '059X XXX XXX',
            self::PF => '87 XX XX XX',
            self::QA => '3X XXX XXXX',
            self::SG => '8XXX XXXX',
            self::SH => '6XXX',
            self::SM => '3XX XXX XXX',
            self::SO => '61X XXX XXX',
            self::ST => '98X XXXX',
            self::SI => '03X XXX XXX',
            self::SC => '2XX XXXX',
            self::TJ, self::UZ => '9X XXX XXXX',
            self::TO => '8XXX XXX',
            self::TN => '2X XXX XXX',
            self::TV => '90XXX',
            self::TW => '09XX XXX XXX',
            self::VE => '04XX XXX XXX',
            self::VU => '5XXXX',
            self::WF => '50 XX XX XX',
            self::YE => '7X XXX XXX'
        };
    }

    public function getName(): string
    {
        return __('BsForm::countries.'.$this->value);
    }

    public function getCode(): string
    {
        return $this->value;
    }

    public function getMaxDigits(): int
    {
        return strlen(str_replace(' ', '', $this->getPhonePlaceholder()));
    }

    public function getPrefix(): ?string
    {
        return Str::of($this->getPhonePlaceholder())->match('/^\d+/')->value();
    }

    public static function all(): array
    {
        return self::cases();
    }
}
